"""
app.py — Streamlit UI for the Oncology RWE Co-Scientist Agent
"""

import streamlit as st
import base64
from PIL import Image
import io
from src.agent import run_agent

st.set_page_config(
    page_title="Oncology RWE Co-Scientist",
    page_icon="🔬",
    layout="wide"
)

st.title("🔬 Oncology RWE Co-Scientist")
st.markdown("""
An AI-powered research agent that analyzes real-world breast cancer survival data 
using Kaplan-Meier curves, Cox PH models, and ML prediction.

**Dataset:** METABRIC (n=496 patients, median follow-up 7.8 years)
""")

# ── Sidebar ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("Example Questions")
    examples = [
        "What clinical factors are most prognostic for survival in this cohort?",
        "Compare survival by molecular subtype and explain the clinical implications.",
        "Run a full survival analysis including KM curves, Cox model, and ML prediction.",
        "Is hormone therapy associated with better survival? Control for confounders.",
        "Which patients are at highest risk of dying within 5 years?",
    ]
    for ex in examples:
        if st.button(ex, use_container_width=True):
            st.session_state["question"] = ex

    st.divider()
    st.markdown("**Data source:** [METABRIC via cBioPortal](https://www.cbioportal.org/study/summary?id=brca_metabric)")
    st.markdown("**Agent:** Claude Sonnet + LangGraph")

# ── Main input ─────────────────────────────────────────────────────────────────
question = st.text_area(
    "Ask a clinical research question:",
    value=st.session_state.get("question", ""),
    height=100,
    placeholder="e.g. What factors predict breast cancer survival in this cohort?"
)

if st.button("🔍 Run Analysis", type="primary", use_container_width=True):
    if not question.strip():
        st.warning("Please enter a research question.")
    else:
        with st.spinner("🤖 Co-scientist is analyzing..."):
            result = run_agent(question)

        st.divider()

        # ── Response ───────────────────────────────────────────────────────────
        st.subheader("📋 Scientific Report")
        st.markdown(result["response"])

        # ── Plots ─────────────────────────────────────────────────────────────
        if result["plots"]:
            st.subheader("📊 Figures")
            cols = st.columns(min(len(result["plots"]), 2))
            for i, plot_b64 in enumerate(result["plots"]):
                img_data = base64.b64decode(plot_b64)
                img = Image.open(io.BytesIO(img_data))
                cols[i % 2].image(img, width=600)

        # ── Download report ────────────────────────────────────────────────────────
        st.divider()
        report_md = f"""# Oncology RWE Analysis Report

        ## Research Question
        {question}

        ## Scientific Findings
        {result["response"]}

        ---
        *Generated by Oncology RWE Co-Scientist — METABRIC dataset (n=496)*
        *Agent: Claude Sonnet + LangGraph*
        """
        st.download_button(
            label="⬇️ Download Report (Markdown)",
            data=report_md,
            file_name="rwe_analysis_report.md",
            mime="text/markdown",
            use_container_width=True
        )        

        # ── Agent trace ────────────────────────────────────────────────────────
        with st.expander("🔎 Agent reasoning trace"):
            for msg in result["messages"]:
                role = type(msg).__name__
                if hasattr(msg, "tool_calls") and msg.tool_calls:
                    for tc in msg.tool_calls:
                        st.info(f"🔧 **Tool called:** `{tc['name']}`  \n**Input:** `{tc['args']}`")
                elif hasattr(msg, "content") and msg.content:
                    content = msg.content
                    if isinstance(content, list):
                        text = " ".join([b.get("text", "") for b in content
                                        if isinstance(b, dict) and "text" in b])
                    else:
                        text = str(content)
                    if text.strip() and role != "ToolMessage":
                        st.markdown(f"**{role}:** {text[:500]}...")